/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.cab.libmgmt.ui;

import com.cab.libmgmt.dao.StudentDAO;
import com.cab.libmgmt.dao.TestScoreDAO;
import com.cab.libmgmt.dbUtils.DBUtils;
import java.sql.ResultSet;

/**
 *
 * @author Jack Sparrow
 */
public class AttendanceView extends javax.swing.JPanel {

    /**
     * Creates new form AttendanceView
     */
    
    private String loadQuery;

    public String getLoadQuery() {
        return loadQuery;
    }

    public void setLoadQuery(String loadQuery) {
        this.loadQuery = loadQuery;
    }
    public AttendanceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidLbl = new javax.swing.JLabel();
        idComboBox = new javax.swing.JComboBox();
        semesterLbl = new javax.swing.JLabel();
        semesterComboBox = new javax.swing.JComboBox();
        viewReportBtn = new javax.swing.JButton();
        tableScroll = new javax.swing.JScrollPane();
        displayTbl = new javax.swing.JTable();

        sidLbl.setText("SID :");

        idComboBox.setModel(new javax.swing.DefaultComboBoxModel(new StudentDAO().selectUniqueIds()));
        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });
        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });

        semesterLbl.setText("Semester:");

        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        semesterComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                semesterComboBoxItemStateChanged(evt);
            }
        });
        semesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterComboBoxActionPerformed(evt);
            }
        });

        viewReportBtn.setText("View Report");
        viewReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportBtnActionPerformed(evt);
            }
        });

        tableScroll.setEnabled(false);

        tableScroll.setViewportView(displayTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewReportBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sidLbl)
                        .addGap(5, 5, 5)
                        .addComponent(idComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(semesterLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sidLbl)
                    .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterLbl))
                .addGap(18, 18, 18)
                .addComponent(viewReportBtn)
                .addGap(29, 29, 29)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idComboBoxActionPerformed

    private void semesterComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_semesterComboBoxItemStateChanged

    }//GEN-LAST:event_semesterComboBoxItemStateChanged

    private void semesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterComboBoxActionPerformed

    }//GEN-LAST:event_semesterComboBoxActionPerformed

    private void viewReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportBtnActionPerformed

        String tempSid = idComboBox.getSelectedItem().toString();
        int sem = Integer.parseInt(semesterComboBox.getSelectedItem().toString());

        String tempQuery = "select * from attendance where sid ='"+tempSid+
        "'and sem="+sem;

        setLoadQuery(tempQuery);
        displayTbl.setModel(DBUtils.buildTableModel(dataExtractHelper()));

    }//GEN-LAST:event_viewReportBtnActionPerformed

    public ResultSet dataExtractHelper(){
        ResultSet rs= null;
        String query = getLoadQuery();
        rs = new TestScoreDAO().loadDbData(query);
        return rs;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable displayTbl;
    private javax.swing.JComboBox idComboBox;
    private javax.swing.JComboBox semesterComboBox;
    private javax.swing.JLabel semesterLbl;
    private javax.swing.JLabel sidLbl;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JButton viewReportBtn;
    // End of variables declaration//GEN-END:variables
}
