/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.cab.libmgmt.ui;

import com.cab.libmgmt.controller.Controller;
import com.cab.libmgmt.dto.StudentDTO;

/**
 *
 * @author Jack Sparrow
 */
public class CRUDAuthenticateUsers extends javax.swing.JFrame {

    /**
     * Creates new form StudentRecord
     */
    public CRUDAuthenticateUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        mainMenuBar = new javax.swing.JMenuBar();
        studentMenu = new javax.swing.JMenu();
        newStudentMenuItem = new javax.swing.JMenuItem();
        updateById = new javax.swing.JMenuItem();
        delteById = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        testScoreEntrySubMenu = new javax.swing.JMenuItem();
        testScoreViewSubMenu = new javax.swing.JMenuItem();
        internalMarksEntryMenu = new javax.swing.JMenuItem();
        attendanceMenu = new javax.swing.JMenu();
        attendanceEntrySubMenu = new javax.swing.JMenuItem();
        attendanceViewSubMenu = new javax.swing.JMenuItem();
        presentationMenu = new javax.swing.JMenu();
        presenationEntrySubMenu = new javax.swing.JMenuItem();
        presenationViewSubMenu = new javax.swing.JMenuItem();
        assignmnetMenu = new javax.swing.JMenu();
        assignmentEntrySubMenu = new javax.swing.JMenuItem();
        assignmentViewSubMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Record");

        studentMenu.setText("Student");

        newStudentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newStudentMenuItem.setText("New Student");
        newStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentMenuItemActionPerformed(evt);
            }
        });
        studentMenu.add(newStudentMenuItem);

        updateById.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        updateById.setText("Update Student");
        updateById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateByIdActionPerformed(evt);
            }
        });
        studentMenu.add(updateById);

        delteById.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        delteById.setText("Delete Student");
        delteById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delteByIdActionPerformed(evt);
            }
        });
        studentMenu.add(delteById);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("View Student");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        studentMenu.add(jMenuItem2);

        mainMenuBar.add(studentMenu);

        jMenu2.setText("Test Score");

        testScoreEntrySubMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        testScoreEntrySubMenu.setText("Test Score Entry");
        testScoreEntrySubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testScoreEntrySubMenuActionPerformed(evt);
            }
        });
        jMenu2.add(testScoreEntrySubMenu);

        testScoreViewSubMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        testScoreViewSubMenu.setText("Test Score View");
        testScoreViewSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testScoreViewSubMenuActionPerformed(evt);
            }
        });
        jMenu2.add(testScoreViewSubMenu);

        internalMarksEntryMenu.setText("Internal Marks Entry");
        internalMarksEntryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internalMarksEntryMenuActionPerformed(evt);
            }
        });
        jMenu2.add(internalMarksEntryMenu);

        mainMenuBar.add(jMenu2);

        attendanceMenu.setText("Attendance");

        attendanceEntrySubMenu.setText("Attendance Entry");
        attendanceEntrySubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceEntrySubMenuActionPerformed(evt);
            }
        });
        attendanceMenu.add(attendanceEntrySubMenu);

        attendanceViewSubMenu.setText("Attendance View");
        attendanceViewSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceViewSubMenuActionPerformed(evt);
            }
        });
        attendanceMenu.add(attendanceViewSubMenu);

        mainMenuBar.add(attendanceMenu);

        presentationMenu.setText("Presentation");

        presenationEntrySubMenu.setText(" Presentation Entry");
        presenationEntrySubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presenationEntrySubMenuActionPerformed(evt);
            }
        });
        presentationMenu.add(presenationEntrySubMenu);

        presenationViewSubMenu.setText(" Presenation View");
        presenationViewSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presenationViewSubMenuActionPerformed(evt);
            }
        });
        presentationMenu.add(presenationViewSubMenu);

        mainMenuBar.add(presentationMenu);

        assignmnetMenu.setText("Assignment");

        assignmentEntrySubMenu.setText("Assignment Entry");
        assignmentEntrySubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentEntrySubMenuActionPerformed(evt);
            }
        });
        assignmnetMenu.add(assignmentEntrySubMenu);

        assignmentViewSubMenu.setText("Assignment View");
        assignmentViewSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentViewSubMenuActionPerformed(evt);
            }
        });
        assignmnetMenu.add(assignmentViewSubMenu);

        mainMenuBar.add(assignmnetMenu);

        helpMenu.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("About US");
        helpMenu.add(jMenuItem1);

        mainMenuBar.add(helpMenu);

        jMenu1.setText("Session");

        jMenuItem4.setText("Log Out");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        mainMenuBar.add(jMenu1);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentMenuItemActionPerformed
        this.setContentPane(new StudentEntry());
        this.validate();
    }//GEN-LAST:event_newStudentMenuItemActionPerformed

    private void updateByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateByIdActionPerformed
        this.setContentPane(new studentUpdateById());
        this.validate();
    }//GEN-LAST:event_updateByIdActionPerformed

    private void delteByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delteByIdActionPerformed
        this.setContentPane(new StudentDeleteByID());
        this.validate();
    }//GEN-LAST:event_delteByIdActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setContentPane(new StudentViewByID1());
        this.validate();
    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void testScoreEntrySubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testScoreEntrySubMenuActionPerformed
        // TODO add your handling code here:
        this.setContentPane(new TestScoreEntry());
        this.validate();
    }//GEN-LAST:event_testScoreEntrySubMenuActionPerformed

    private void testScoreViewSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testScoreViewSubMenuActionPerformed
        this.setContentPane(new TestScoreView());
        this.validate();
        // TODO add your handling code here:
    }//GEN-LAST:event_testScoreViewSubMenuActionPerformed

    private void attendanceEntrySubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceEntrySubMenuActionPerformed
       this.setContentPane(new AttendanceEntry());
        this.validate();
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceEntrySubMenuActionPerformed

    private void attendanceViewSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceViewSubMenuActionPerformed
        this.setContentPane(new AttendanceView());
        this.validate();
           // TODO add your handling code here:
    }//GEN-LAST:event_attendanceViewSubMenuActionPerformed

    private void presenationEntrySubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presenationEntrySubMenuActionPerformed

         this.setContentPane(new PresentationEntry());
        this.validate();
            // TODO add your handling code here:
    }//GEN-LAST:event_presenationEntrySubMenuActionPerformed

    private void presenationViewSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presenationViewSubMenuActionPerformed
       
        this.setContentPane(new PresentationView());
        this.validate();
// TODO add your handling code here:
    }//GEN-LAST:event_presenationViewSubMenuActionPerformed

    private void assignmentEntrySubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentEntrySubMenuActionPerformed
        this.setContentPane(new AssignmentEntry());
        this.validate();
// TODO add your handling code here:
    }//GEN-LAST:event_assignmentEntrySubMenuActionPerformed

    private void assignmentViewSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentViewSubMenuActionPerformed
       this.setContentPane(new AssignmentView());
        this.validate(); // TODO add your handling code here:
    }//GEN-LAST:event_assignmentViewSubMenuActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginDialog dialog = new LoginDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void internalMarksEntryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internalMarksEntryMenuActionPerformed
        this.setContentPane(new InternalMarksEntry());
        this.validate();// TODO add your handling code here:
    }//GEN-LAST:event_internalMarksEntryMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem assignmentEntrySubMenu;
    private javax.swing.JMenuItem assignmentViewSubMenu;
    private javax.swing.JMenu assignmnetMenu;
    private javax.swing.JMenuItem attendanceEntrySubMenu;
    private javax.swing.JMenu attendanceMenu;
    private javax.swing.JMenuItem attendanceViewSubMenu;
    private javax.swing.JMenuItem delteById;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem internalMarksEntryMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem newStudentMenuItem;
    private javax.swing.JMenuItem presenationEntrySubMenu;
    private javax.swing.JMenuItem presenationViewSubMenu;
    private javax.swing.JMenu presentationMenu;
    private javax.swing.JMenu studentMenu;
    private javax.swing.JMenuItem testScoreEntrySubMenu;
    private javax.swing.JMenuItem testScoreViewSubMenu;
    private javax.swing.JMenuItem updateById;
    // End of variables declaration//GEN-END:variables
}
