/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.cab.libmgmt.ui;
import com.cab.libmgmt.controller.UserController;
import com.cab.libmgmt.dao.UserDAO;
import com.cab.libmgmt.dbUtils.DBUtils;
import javax.swing.JOptionPane;
/**
 *
 * @author Jack Sparrow
 */
public class DelteUser extends javax.swing.JPanel {

    /**
     * Creates new form DelteUser
     */
    public DelteUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tableScroll = new javax.swing.JScrollPane();
        displayTbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Available Users:");

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        displayTbl.setModel(DBUtils.buildTableModel(new UserDAO().loadDbData()));
        tableScroll.setViewportView(displayTbl);

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Note : Please Do Not Delete \"admin\" account. Thank You");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                            
        String id = (String) displayTbl.getValueAt(displayTbl.getSelectedRow(), 0);
        if(new UserDAO().delete(id)){
            JOptionPane.showMessageDialog(controlPanel, "Deleted...");
        }
        loadTable();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadTable(){
        displayTbl.setModel(DBUtils.buildTableModel(new UserDAO().loadDbData()));
    }
    
     private javax.swing.JPanel controlPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable displayTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane tableScroll;
    // End of variables declaration//GEN-END:variables
}
