/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.cab.libmgmt.ui;

import com.cab.libmgmt.controller.AttendanceController;
import com.cab.libmgmt.controller.PresentationController;
import com.cab.libmgmt.dao.StudentDAO;
import com.cab.libmgmt.dto.AttendanceDTO;
import com.cab.libmgmt.dto.PresentationDTO;

/**
 *
 * @author Jack Sparrow
 */
public class PresentationEntry extends javax.swing.JPanel {

    /**
     * Creates new form TestScoreEntry
     */
    public PresentationEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idComboBox = new javax.swing.JComboBox();
        sidLbl = new javax.swing.JLabel();
        semesterComboBox = new javax.swing.JComboBox();
        semesterLbl = new javax.swing.JLabel();
        monthLbl = new javax.swing.JLabel();
        PresentationCombo = new javax.swing.JComboBox();
        percentLbl = new javax.swing.JLabel();
        insertRecordBtn = new javax.swing.JButton();
        percentageTxtField = new javax.swing.JTextField();
        scoreComboBox1 = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Insert Test Score"));

        idComboBox.setModel(new javax.swing.DefaultComboBoxModel(new StudentDAO().selectUniqueIds()));
        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });
        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });

        sidLbl.setText("SID :");

        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        semesterComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                semesterComboBoxItemStateChanged(evt);
            }
        });
        semesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterComboBoxActionPerformed(evt);
            }
        });

        semesterLbl.setText("Semester:");

        monthLbl.setText("Presentation No.");

        PresentationCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        percentLbl.setText("Score:");

        insertRecordBtn.setText("Insert Record");
        insertRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertRecordBtnActionPerformed(evt);
            }
        });

        scoreComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthLbl)
                            .addComponent(sidLbl))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PresentationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentLbl)
                            .addComponent(semesterLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(semesterComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(percentageTxtField))
                        .addGap(18, 18, 18)
                        .addComponent(scoreComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(insertRecordBtn))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sidLbl)
                    .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentLbl)
                    .addComponent(monthLbl)
                    .addComponent(PresentationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(insertRecordBtn)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idComboBoxActionPerformed

    private void semesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterComboBoxActionPerformed
        
    }//GEN-LAST:event_semesterComboBoxActionPerformed

    private void insertRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertRecordBtnActionPerformed
        
        // TODO add your handling code here:
        String tempSid;
        
        tempSid = idComboBox.getSelectedItem().toString();
        
         
       
        int presentationNum = Integer.parseInt(PresentationCombo.getSelectedItem().toString());
        int sem = Integer.parseInt(semesterComboBox.getSelectedItem().toString());
        int score = Integer.parseInt(scoreComboBox1.getSelectedItem().toString());
        //Integer.parseInt(percentageTxtField.toString());
        //transfering data to Data Transfer Object
        PresentationDTO psDTO = new PresentationDTO();
        psDTO.setSid(tempSid);
        psDTO.setPresentationNum(presentationNum);
        psDTO.setScore(score);
        psDTO.setSemester(sem);
        
        PresentationController ps = new PresentationController();
        ps.controlTestScore(tempSid, psDTO);
    }//GEN-LAST:event_insertRecordBtnActionPerformed

    private void semesterComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_semesterComboBoxItemStateChanged
       
    }//GEN-LAST:event_semesterComboBoxItemStateChanged


    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox PresentationCombo;
    private javax.swing.JComboBox idComboBox;
    private javax.swing.JButton insertRecordBtn;
    private javax.swing.JLabel monthLbl;
    private javax.swing.JLabel percentLbl;
    private javax.swing.JTextField percentageTxtField;
    private javax.swing.JComboBox scoreComboBox1;
    private javax.swing.JComboBox semesterComboBox;
    private javax.swing.JLabel semesterLbl;
    private javax.swing.JLabel sidLbl;
    // End of variables declaration//GEN-END:variables
}
