/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cab.libmgmt.ui;

import com.cab.libmgmt.controller.Controller;
import com.cab.libmgmt.dao.Credential;
import com.cab.libmgmt.dto.StudentDTO;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author Jack Sparrow
 */
public class StudentEntry extends javax.swing.JPanel {

    /**
     * Creates new form StudentEntry
     */
    private String tempUrl;

    public String getTempUrl() {
        
        return tempUrl;
    }

    public void setTempUrl(String tempUrl) {
        String extraTempUrl = "";
        if (tempUrl != null && !tempUrl.isEmpty()) {
            for (char c : tempUrl.toCharArray()) {
                if (c != '\\') {
                    extraTempUrl += c;
                } else {
                    extraTempUrl += "\\\\";
                }
            }

        }
        
        this.tempUrl = extraTempUrl;
    }

    public StudentEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        saveBttn = new javax.swing.JButton();
        sidLbl = new javax.swing.JLabel();
        sidText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        picChooserBtn = new javax.swing.JButton();
        purush = new javax.swing.JRadioButton();
        stri = new javax.swing.JRadioButton();
        genderLbl = new javax.swing.JLabel();
        dobLbl = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        profilePicLbl = new javax.swing.JLabel();
        pwdTxt = new javax.swing.JTextField();
        pwdLbl = new javax.swing.JLabel();

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Info"));

        nameLbl.setText("Name");

        phoneLbl.setText("Phone");

        addressLbl.setText("Address:");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        phoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxtActionPerformed(evt);
            }
        });

        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });

        saveBttn.setText("Save");
        saveBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBttnActionPerformed(evt);
            }
        });

        sidLbl.setText("SID:");

        sidText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidTextActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        picChooserBtn.setText("Choose Picture");
        picChooserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picChooserBtnActionPerformed(evt);
            }
        });

        gender.add(purush);
        purush.setSelected(true);
        purush.setText("Male");

        gender.add(stri);
        stri.setText("Female");

        genderLbl.setText("Gender:");

        dobLbl.setText("Date of Birth:");

        profilePicLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        profilePicLbl.setText("Profile Picture");

        pwdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdTxtActionPerformed(evt);
            }
        });

        pwdLbl.setText("Password");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLbl)
                    .addComponent(phoneLbl)
                    .addComponent(addressLbl)
                    .addComponent(sidLbl)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dobLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(genderLbl))
                    .addComponent(pwdLbl))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(purush)
                        .addGap(18, 18, 18)
                        .addComponent(stri))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addressTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phoneTxt))
                    .addComponent(saveBttn)
                    .addComponent(sidText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(picChooserBtn)
                        .addGap(80, 80, 80))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(profilePicLbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sidLbl)
                    .addComponent(sidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLbl)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobLbl)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purush)
                    .addComponent(stri)
                    .addComponent(genderLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdLbl)
                    .addComponent(pwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(profilePicLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picChooserBtn)
                    .addComponent(saveBttn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBttnActionPerformed
        String sid = sidText.getText();
        String name = nameTxt.getText();
        String phone = phoneTxt.getText();
        String address = addressTxt.getText();
        
        Date date = jDateChooser1.getDate();
        String strDate = DateFormat.getDateInstance().format(date);
        
        String genderName = getSelectedButtonText(gender);
        
        StudentDTO st = new StudentDTO();
        st.setSid(sid);
        st.setName(name);
        st.setPhone(phone);
        st.setAddress(address);
        st.setDob(strDate);
        st.setGender(genderName);
        
        //setting URL
        st.setUrl(getTempUrl());
        
        String password = pwdTxt.getText();
        new Credential().inputCredential(sid, password);
        
        
        Controller controller = new Controller();
        controller.controlStudents("insert", st);
    }//GEN-LAST:event_saveBttnActionPerformed

    public String getSelectedButtonText(ButtonGroup gender) {
        for (Enumeration<AbstractButton> buttons = gender.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void phoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxtActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void picChooserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picChooserBtnActionPerformed
        uploadFileChooser = new JFileChooser();
        if (uploadFileChooser.showOpenDialog(this) == 0) {

            try {
                File selectedFile = uploadFileChooser.getSelectedFile();
                ImageIcon ii = new ImageIcon(new ScaleImage().scaleImage(180, 135, ImageIO.read(selectedFile)));
                setTempUrl(selectedFile.getAbsolutePath());
                jLabel1.setIcon(ii);
            } catch (IOException ex) {
                Logger.getLogger(StudentEntry.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(StudentEntry.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_picChooserBtnActionPerformed

    private void pwdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdTxtActionPerformed

    private void sidTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidTextActionPerformed

    public JTextField getEmailTxt() {
        return addressTxt;
    }

    public void setEmailTxt(String email) {
        this.addressTxt.setText(email);
    }

    public JTextField getNameTxt() {
        return nameTxt;
    }

    public void setNameTxt(String name) {
        this.nameTxt.setText(name);
    }

    public JTextField getPhoneTxt() {
        return phoneTxt;
    }

    public void setPhoneTxt(String phone) {
        this.phoneTxt.setText(phone);
    }

    public void setSaveBttnText(String value) {
        this.saveBttn.setText(value);
    }

    private String[] dayDate(){
        String[] day = null;
        for(int i=1;i<=32;i++){
        
        }
        
        
        
        return day;
    }
    
    
    private javax.swing.JFileChooser uploadFileChooser;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel dobLbl;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel genderLbl;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton picChooserBtn;
    private javax.swing.JLabel profilePicLbl;
    private javax.swing.JRadioButton purush;
    private javax.swing.JLabel pwdLbl;
    private javax.swing.JTextField pwdTxt;
    private javax.swing.JButton saveBttn;
    private javax.swing.JLabel sidLbl;
    private javax.swing.JTextField sidText;
    private javax.swing.JRadioButton stri;
    // End of variables declaration//GEN-END:variables
}
