/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.cab.libmgmt.ui;

import com.cab.libmgmt.dao.StudentDAO;
import com.cab.libmgmt.dao.TestScoreDAO;
import com.cab.libmgmt.dbUtils.DBUtils;
import java.sql.ResultSet;
/**
 *
 * @author Jack Sparrow
 */
public class TestScoreView extends javax.swing.JPanel {

    
    private String loadQuery;

    public String getLoadQuery() {
        return loadQuery;
    }

    public void setLoadQuery(String loadQuery) {
        this.loadQuery = loadQuery;
    }
    /**
     * Creates new form TestScoreView
     */
    public TestScoreView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idComboBox = new javax.swing.JComboBox();
        sidLbl = new javax.swing.JLabel();
        semesterLbl = new javax.swing.JLabel();
        semesterComboBox = new javax.swing.JComboBox();
        testNoComboBox = new javax.swing.JComboBox();
        testLbl = new javax.swing.JLabel();
        viewReportBtn = new javax.swing.JButton();
        tableScroll = new javax.swing.JScrollPane();
        displayTbl = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "View Test Score"));

        idComboBox.setModel(new javax.swing.DefaultComboBoxModel(new StudentDAO().selectUniqueIds()));
        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });
        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });

        sidLbl.setText("SID :");

        semesterLbl.setText("Semester:");

        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        semesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterComboBoxActionPerformed(evt);
            }
        });

        testNoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        testLbl.setText("Test No. :");

        viewReportBtn.setText("View Report");
        viewReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportBtnActionPerformed(evt);
            }
        });

        tableScroll.setEnabled(false);

        tableScroll.setViewportView(displayTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sidLbl)
                        .addGap(28, 28, 28)
                        .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewReportBtn))
                .addGap(15, 15, 15)
                .addComponent(semesterLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(testLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testNoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sidLbl)
                    .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterLbl)
                    .addComponent(testLbl)
                    .addComponent(testNoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(viewReportBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idComboBoxActionPerformed

    private void semesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterComboBoxActionPerformed
       
    }//GEN-LAST:event_semesterComboBoxActionPerformed

    private void viewReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportBtnActionPerformed
        
        String tempSid = idComboBox.getSelectedItem().toString();
         
        int test_no = Integer.parseInt(testNoComboBox.getSelectedItem().toString());
        int sem = Integer.parseInt(semesterComboBox.getSelectedItem().toString());
        
        String tempQuery = "select * from test_scores where sid ='"+tempSid+
                "' and test_no="+test_no+" and semester="+sem;
        
        setLoadQuery(tempQuery);
        displayTbl.setModel(DBUtils.buildTableModel(dataExtractHelper()));
            
    }//GEN-LAST:event_viewReportBtnActionPerformed

    public ResultSet dataExtractHelper(){
        ResultSet rs= null;
        String query = getLoadQuery();
        rs = new TestScoreDAO().loadDbData(query);
        return rs;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable displayTbl;
    private javax.swing.JComboBox idComboBox;
    private javax.swing.JComboBox semesterComboBox;
    private javax.swing.JLabel semesterLbl;
    private javax.swing.JLabel sidLbl;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JLabel testLbl;
    private javax.swing.JComboBox testNoComboBox;
    private javax.swing.JButton viewReportBtn;
    // End of variables declaration//GEN-END:variables
}
