/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.cab.libmgmt.ui;

import com.cab.libmgmt.controller.Controller;
import com.cab.libmgmt.dto.StudentDTO;

/**
 *
 * @author Jack Sparrow
 */
public class ViewAuthenticateUsers extends javax.swing.JFrame {

    /**
     * Creates new form StudentRecord
     */
    public ViewAuthenticateUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuBar = new javax.swing.JMenuBar();
        viewMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        testScoreViewSubMenu = new javax.swing.JMenuItem();
        attendanceViewSubMenu1 = new javax.swing.JMenuItem();
        presenationViewSubMenu1 = new javax.swing.JMenuItem();
        assignmentViewSubMenu1 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Record");

        viewMenu.setText("View");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("View Student");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        viewMenu.add(jMenuItem2);

        testScoreViewSubMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        testScoreViewSubMenu.setText("Test Score View");
        testScoreViewSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testScoreViewSubMenuActionPerformed(evt);
            }
        });
        viewMenu.add(testScoreViewSubMenu);

        attendanceViewSubMenu1.setText("Attendance View");
        attendanceViewSubMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceViewSubMenu1ActionPerformed(evt);
            }
        });
        viewMenu.add(attendanceViewSubMenu1);

        presenationViewSubMenu1.setText(" Presenation View");
        presenationViewSubMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presenationViewSubMenu1ActionPerformed(evt);
            }
        });
        viewMenu.add(presenationViewSubMenu1);

        assignmentViewSubMenu1.setText("Assignment View");
        assignmentViewSubMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentViewSubMenu1ActionPerformed(evt);
            }
        });
        viewMenu.add(assignmentViewSubMenu1);

        mainMenuBar.add(viewMenu);

        helpMenu.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("About US");
        helpMenu.add(jMenuItem1);

        mainMenuBar.add(helpMenu);

        jMenu1.setText("Session");

        jMenuItem4.setText("Log Out");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        mainMenuBar.add(jMenu1);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setContentPane(new StudentViewByID1());
        this.validate();
    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void testScoreViewSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testScoreViewSubMenuActionPerformed
        this.setContentPane(new TestScoreView());
        this.validate();
        // TODO add your handling code here:
    }//GEN-LAST:event_testScoreViewSubMenuActionPerformed

    private void attendanceViewSubMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceViewSubMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceViewSubMenu1ActionPerformed

    private void presenationViewSubMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presenationViewSubMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presenationViewSubMenu1ActionPerformed

    private void assignmentViewSubMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentViewSubMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentViewSubMenu1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginDialog dialog = new LoginDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem assignmentViewSubMenu1;
    private javax.swing.JMenuItem attendanceViewSubMenu1;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem presenationViewSubMenu1;
    private javax.swing.JMenuItem testScoreViewSubMenu;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
